/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationTanstackQueryRouteImport } from './routes/integration/tanstack-query'
import { Route as IntegrationTableRouteImport } from './routes/integration/table'
import { Route as IntegrationStoreRouteImport } from './routes/integration/store'
import { Route as IntegrationMcpTodosRouteImport } from './routes/integration/mcp-todos'
import { Route as IntegrationDrizzleRouteImport } from './routes/integration/drizzle'
import { Route as IntegrationAiStructuredRouteImport } from './routes/integration/ai-structured'
import { Route as IntegrationAiImageRouteImport } from './routes/integration/ai-image'
import { Route as IntegrationAiChatRouteImport } from './routes/integration/ai-chat'
import { Route as DemoTodoRouteImport } from './routes/demo/todo'
import { Route as ApiTodoRouteImport } from './routes/api/todo'
import { Route as ApiMessageRouteImport } from './routes/api/message'
import { Route as ApiFriend_requestRouteImport } from './routes/api/friend_request'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as IntegrationGuitarsIndexRouteImport } from './routes/integration/guitars/index'
import { Route as IntegrationBetterAuthIndexRouteImport } from './routes/integration/better-auth/index'
import { Route as DemoChatIndexRouteImport } from './routes/demo/chat/index'
import { Route as BaseS3IndexRouteImport } from './routes/base/s3/index'
import { Route as UiActionButtonRouteImport } from './routes/ui/action/button'
import { Route as IntegrationZodFileRouteImport } from './routes/integration/zod/file'
import { Route as IntegrationTanstackDbErrorRouteImport } from './routes/integration/tanstack-db/error'
import { Route as IntegrationTanstackDbChatApiRouteImport } from './routes/integration/tanstack-db/chat-api'
import { Route as IntegrationTanstackDbChatRouteImport } from './routes/integration/tanstack-db/chat'
import { Route as IntegrationOrpcTodoRouteImport } from './routes/integration/orpc/todo'
import { Route as IntegrationI18nParaglideRouteImport } from './routes/integration/i18n/paraglide'
import { Route as IntegrationGuitarsGuitarIdRouteImport } from './routes/integration/guitars/$guitarId'
import { Route as IntegrationFormSimpleRouteImport } from './routes/integration/form/simple'
import { Route as IntegrationFormAddressRouteImport } from './routes/integration/form/address'
import { Route as IntegrationBetterAuthWebauthnRouteImport } from './routes/integration/better-auth/webauthn'
import { Route as IntegrationApiMcpTodosRouteImport } from './routes/integration/api.mcp-todos'
import { Route as BaseHttpXhrRouteImport } from './routes/base/http/xhr'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoChatDmRouteRouteImport } from './routes/demo/chat/_dm/route'
import { Route as UiDisplayMdIndexRouteImport } from './routes/ui/display/md/index'
import { Route as UiDisplayMdTiptapRouteImport } from './routes/ui/display/md/tiptap'
import { Route as IntegrationApiAiTtsRouteImport } from './routes/integration/api.ai.tts'
import { Route as IntegrationApiAiTranscriptionRouteImport } from './routes/integration/api.ai.transcription'
import { Route as IntegrationApiAiStructuredRouteImport } from './routes/integration/api.ai.structured'
import { Route as IntegrationApiAiImageRouteImport } from './routes/integration/api.ai.image'
import { Route as IntegrationApiAiChatRouteImport } from './routes/integration/api.ai.chat'
import { Route as DemoChatDmDmRouteImport } from './routes/demo/chat/_dm/dm'
import { Route as BaseHttpApiErrRouteImport } from './routes/base/http/api.err'
import { Route as UiDisplayMdProsemirrorIndexRouteImport } from './routes/ui/display/md/prosemirror/index'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationTanstackQueryRoute =
  IntegrationTanstackQueryRouteImport.update({
    id: '/integration/tanstack-query',
    path: '/integration/tanstack-query',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationTableRoute = IntegrationTableRouteImport.update({
  id: '/integration/table',
  path: '/integration/table',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationStoreRoute = IntegrationStoreRouteImport.update({
  id: '/integration/store',
  path: '/integration/store',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationMcpTodosRoute = IntegrationMcpTodosRouteImport.update({
  id: '/integration/mcp-todos',
  path: '/integration/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationDrizzleRoute = IntegrationDrizzleRouteImport.update({
  id: '/integration/drizzle',
  path: '/integration/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationAiStructuredRoute = IntegrationAiStructuredRouteImport.update({
  id: '/integration/ai-structured',
  path: '/integration/ai-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationAiImageRoute = IntegrationAiImageRouteImport.update({
  id: '/integration/ai-image',
  path: '/integration/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationAiChatRoute = IntegrationAiChatRouteImport.update({
  id: '/integration/ai-chat',
  path: '/integration/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTodoRoute = DemoTodoRouteImport.update({
  id: '/demo/todo',
  path: '/demo/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodoRoute = ApiTodoRouteImport.update({
  id: '/api/todo',
  path: '/api/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessageRoute = ApiMessageRouteImport.update({
  id: '/api/message',
  path: '/api/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFriend_requestRoute = ApiFriend_requestRouteImport.update({
  id: '/api/friend_request',
  path: '/api/friend_request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationGuitarsIndexRoute = IntegrationGuitarsIndexRouteImport.update({
  id: '/integration/guitars/',
  path: '/integration/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationBetterAuthIndexRoute =
  IntegrationBetterAuthIndexRouteImport.update({
    id: '/integration/better-auth/',
    path: '/integration/better-auth/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoChatIndexRoute = DemoChatIndexRouteImport.update({
  id: '/demo/chat/',
  path: '/demo/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseS3IndexRoute = BaseS3IndexRouteImport.update({
  id: '/base/s3/',
  path: '/base/s3/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiActionButtonRoute = UiActionButtonRouteImport.update({
  id: '/ui/action/button',
  path: '/ui/action/button',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationZodFileRoute = IntegrationZodFileRouteImport.update({
  id: '/integration/zod/file',
  path: '/integration/zod/file',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationTanstackDbErrorRoute =
  IntegrationTanstackDbErrorRouteImport.update({
    id: '/integration/tanstack-db/error',
    path: '/integration/tanstack-db/error',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationTanstackDbChatApiRoute =
  IntegrationTanstackDbChatApiRouteImport.update({
    id: '/integration/tanstack-db/chat-api',
    path: '/integration/tanstack-db/chat-api',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationTanstackDbChatRoute =
  IntegrationTanstackDbChatRouteImport.update({
    id: '/integration/tanstack-db/chat',
    path: '/integration/tanstack-db/chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationOrpcTodoRoute = IntegrationOrpcTodoRouteImport.update({
  id: '/integration/orpc/todo',
  path: '/integration/orpc/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationI18nParaglideRoute =
  IntegrationI18nParaglideRouteImport.update({
    id: '/integration/i18n/paraglide',
    path: '/integration/i18n/paraglide',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationGuitarsGuitarIdRoute =
  IntegrationGuitarsGuitarIdRouteImport.update({
    id: '/integration/guitars/$guitarId',
    path: '/integration/guitars/$guitarId',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationFormSimpleRoute = IntegrationFormSimpleRouteImport.update({
  id: '/integration/form/simple',
  path: '/integration/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationFormAddressRoute = IntegrationFormAddressRouteImport.update({
  id: '/integration/form/address',
  path: '/integration/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationBetterAuthWebauthnRoute =
  IntegrationBetterAuthWebauthnRouteImport.update({
    id: '/integration/better-auth/webauthn',
    path: '/integration/better-auth/webauthn',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationApiMcpTodosRoute = IntegrationApiMcpTodosRouteImport.update({
  id: '/integration/api/mcp-todos',
  path: '/integration/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseHttpXhrRoute = BaseHttpXhrRouteImport.update({
  id: '/base/http/xhr',
  path: '/base/http/xhr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoChatDmRouteRoute = DemoChatDmRouteRouteImport.update({
  id: '/demo/chat/_dm',
  path: '/demo/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const UiDisplayMdIndexRoute = UiDisplayMdIndexRouteImport.update({
  id: '/ui/display/md/',
  path: '/ui/display/md/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiDisplayMdTiptapRoute = UiDisplayMdTiptapRouteImport.update({
  id: '/ui/display/md/tiptap',
  path: '/ui/display/md/tiptap',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationApiAiTtsRoute = IntegrationApiAiTtsRouteImport.update({
  id: '/integration/api/ai/tts',
  path: '/integration/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationApiAiTranscriptionRoute =
  IntegrationApiAiTranscriptionRouteImport.update({
    id: '/integration/api/ai/transcription',
    path: '/integration/api/ai/transcription',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationApiAiStructuredRoute =
  IntegrationApiAiStructuredRouteImport.update({
    id: '/integration/api/ai/structured',
    path: '/integration/api/ai/structured',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationApiAiImageRoute = IntegrationApiAiImageRouteImport.update({
  id: '/integration/api/ai/image',
  path: '/integration/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationApiAiChatRoute = IntegrationApiAiChatRouteImport.update({
  id: '/integration/api/ai/chat',
  path: '/integration/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoChatDmDmRoute = DemoChatDmDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => DemoChatDmRouteRoute,
} as any)
const BaseHttpApiErrRoute = BaseHttpApiErrRouteImport.update({
  id: '/base/http/api/err',
  path: '/base/http/api/err',
  getParentRoute: () => rootRouteImport,
} as any)
const UiDisplayMdProsemirrorIndexRoute =
  UiDisplayMdProsemirrorIndexRouteImport.update({
    id: '/ui/display/md/prosemirror/',
    path: '/ui/display/md/prosemirror/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/friend_request': typeof ApiFriend_requestRoute
  '/api/message': typeof ApiMessageRoute
  '/api/todo': typeof ApiTodoRoute
  '/demo/todo': typeof DemoTodoRoute
  '/integration/ai-chat': typeof IntegrationAiChatRoute
  '/integration/ai-image': typeof IntegrationAiImageRoute
  '/integration/ai-structured': typeof IntegrationAiStructuredRoute
  '/integration/drizzle': typeof IntegrationDrizzleRoute
  '/integration/mcp-todos': typeof IntegrationMcpTodosRoute
  '/integration/store': typeof IntegrationStoreRoute
  '/integration/table': typeof IntegrationTableRoute
  '/integration/tanstack-query': typeof IntegrationTanstackQueryRoute
  '/demo/chat': typeof DemoChatDmRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/base/http/xhr': typeof BaseHttpXhrRoute
  '/integration/api/mcp-todos': typeof IntegrationApiMcpTodosRoute
  '/integration/better-auth/webauthn': typeof IntegrationBetterAuthWebauthnRoute
  '/integration/form/address': typeof IntegrationFormAddressRoute
  '/integration/form/simple': typeof IntegrationFormSimpleRoute
  '/integration/guitars/$guitarId': typeof IntegrationGuitarsGuitarIdRoute
  '/integration/i18n/paraglide': typeof IntegrationI18nParaglideRoute
  '/integration/orpc/todo': typeof IntegrationOrpcTodoRoute
  '/integration/tanstack-db/chat': typeof IntegrationTanstackDbChatRoute
  '/integration/tanstack-db/chat-api': typeof IntegrationTanstackDbChatApiRoute
  '/integration/tanstack-db/error': typeof IntegrationTanstackDbErrorRoute
  '/integration/zod/file': typeof IntegrationZodFileRoute
  '/ui/action/button': typeof UiActionButtonRoute
  '/base/s3/': typeof BaseS3IndexRoute
  '/demo/chat/': typeof DemoChatIndexRoute
  '/integration/better-auth/': typeof IntegrationBetterAuthIndexRoute
  '/integration/guitars/': typeof IntegrationGuitarsIndexRoute
  '/base/http/api/err': typeof BaseHttpApiErrRoute
  '/demo/chat/dm': typeof DemoChatDmDmRoute
  '/integration/api/ai/chat': typeof IntegrationApiAiChatRoute
  '/integration/api/ai/image': typeof IntegrationApiAiImageRoute
  '/integration/api/ai/structured': typeof IntegrationApiAiStructuredRoute
  '/integration/api/ai/transcription': typeof IntegrationApiAiTranscriptionRoute
  '/integration/api/ai/tts': typeof IntegrationApiAiTtsRoute
  '/ui/display/md/tiptap': typeof UiDisplayMdTiptapRoute
  '/ui/display/md/': typeof UiDisplayMdIndexRoute
  '/ui/display/md/prosemirror/': typeof UiDisplayMdProsemirrorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/friend_request': typeof ApiFriend_requestRoute
  '/api/message': typeof ApiMessageRoute
  '/api/todo': typeof ApiTodoRoute
  '/demo/todo': typeof DemoTodoRoute
  '/integration/ai-chat': typeof IntegrationAiChatRoute
  '/integration/ai-image': typeof IntegrationAiImageRoute
  '/integration/ai-structured': typeof IntegrationAiStructuredRoute
  '/integration/drizzle': typeof IntegrationDrizzleRoute
  '/integration/mcp-todos': typeof IntegrationMcpTodosRoute
  '/integration/store': typeof IntegrationStoreRoute
  '/integration/table': typeof IntegrationTableRoute
  '/integration/tanstack-query': typeof IntegrationTanstackQueryRoute
  '/demo/chat': typeof DemoChatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/base/http/xhr': typeof BaseHttpXhrRoute
  '/integration/api/mcp-todos': typeof IntegrationApiMcpTodosRoute
  '/integration/better-auth/webauthn': typeof IntegrationBetterAuthWebauthnRoute
  '/integration/form/address': typeof IntegrationFormAddressRoute
  '/integration/form/simple': typeof IntegrationFormSimpleRoute
  '/integration/guitars/$guitarId': typeof IntegrationGuitarsGuitarIdRoute
  '/integration/i18n/paraglide': typeof IntegrationI18nParaglideRoute
  '/integration/orpc/todo': typeof IntegrationOrpcTodoRoute
  '/integration/tanstack-db/chat': typeof IntegrationTanstackDbChatRoute
  '/integration/tanstack-db/chat-api': typeof IntegrationTanstackDbChatApiRoute
  '/integration/tanstack-db/error': typeof IntegrationTanstackDbErrorRoute
  '/integration/zod/file': typeof IntegrationZodFileRoute
  '/ui/action/button': typeof UiActionButtonRoute
  '/base/s3': typeof BaseS3IndexRoute
  '/integration/better-auth': typeof IntegrationBetterAuthIndexRoute
  '/integration/guitars': typeof IntegrationGuitarsIndexRoute
  '/base/http/api/err': typeof BaseHttpApiErrRoute
  '/demo/chat/dm': typeof DemoChatDmDmRoute
  '/integration/api/ai/chat': typeof IntegrationApiAiChatRoute
  '/integration/api/ai/image': typeof IntegrationApiAiImageRoute
  '/integration/api/ai/structured': typeof IntegrationApiAiStructuredRoute
  '/integration/api/ai/transcription': typeof IntegrationApiAiTranscriptionRoute
  '/integration/api/ai/tts': typeof IntegrationApiAiTtsRoute
  '/ui/display/md/tiptap': typeof UiDisplayMdTiptapRoute
  '/ui/display/md': typeof UiDisplayMdIndexRoute
  '/ui/display/md/prosemirror': typeof UiDisplayMdProsemirrorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/friend_request': typeof ApiFriend_requestRoute
  '/api/message': typeof ApiMessageRoute
  '/api/todo': typeof ApiTodoRoute
  '/demo/todo': typeof DemoTodoRoute
  '/integration/ai-chat': typeof IntegrationAiChatRoute
  '/integration/ai-image': typeof IntegrationAiImageRoute
  '/integration/ai-structured': typeof IntegrationAiStructuredRoute
  '/integration/drizzle': typeof IntegrationDrizzleRoute
  '/integration/mcp-todos': typeof IntegrationMcpTodosRoute
  '/integration/store': typeof IntegrationStoreRoute
  '/integration/table': typeof IntegrationTableRoute
  '/integration/tanstack-query': typeof IntegrationTanstackQueryRoute
  '/demo/chat/_dm': typeof DemoChatDmRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/base/http/xhr': typeof BaseHttpXhrRoute
  '/integration/api/mcp-todos': typeof IntegrationApiMcpTodosRoute
  '/integration/better-auth/webauthn': typeof IntegrationBetterAuthWebauthnRoute
  '/integration/form/address': typeof IntegrationFormAddressRoute
  '/integration/form/simple': typeof IntegrationFormSimpleRoute
  '/integration/guitars/$guitarId': typeof IntegrationGuitarsGuitarIdRoute
  '/integration/i18n/paraglide': typeof IntegrationI18nParaglideRoute
  '/integration/orpc/todo': typeof IntegrationOrpcTodoRoute
  '/integration/tanstack-db/chat': typeof IntegrationTanstackDbChatRoute
  '/integration/tanstack-db/chat-api': typeof IntegrationTanstackDbChatApiRoute
  '/integration/tanstack-db/error': typeof IntegrationTanstackDbErrorRoute
  '/integration/zod/file': typeof IntegrationZodFileRoute
  '/ui/action/button': typeof UiActionButtonRoute
  '/base/s3/': typeof BaseS3IndexRoute
  '/demo/chat/': typeof DemoChatIndexRoute
  '/integration/better-auth/': typeof IntegrationBetterAuthIndexRoute
  '/integration/guitars/': typeof IntegrationGuitarsIndexRoute
  '/base/http/api/err': typeof BaseHttpApiErrRoute
  '/demo/chat/_dm/dm': typeof DemoChatDmDmRoute
  '/integration/api/ai/chat': typeof IntegrationApiAiChatRoute
  '/integration/api/ai/image': typeof IntegrationApiAiImageRoute
  '/integration/api/ai/structured': typeof IntegrationApiAiStructuredRoute
  '/integration/api/ai/transcription': typeof IntegrationApiAiTranscriptionRoute
  '/integration/api/ai/tts': typeof IntegrationApiAiTtsRoute
  '/ui/display/md/tiptap': typeof UiDisplayMdTiptapRoute
  '/ui/display/md/': typeof UiDisplayMdIndexRoute
  '/ui/display/md/prosemirror/': typeof UiDisplayMdProsemirrorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/mcp'
    | '/api/$'
    | '/api/friend_request'
    | '/api/message'
    | '/api/todo'
    | '/demo/todo'
    | '/integration/ai-chat'
    | '/integration/ai-image'
    | '/integration/ai-structured'
    | '/integration/drizzle'
    | '/integration/mcp-todos'
    | '/integration/store'
    | '/integration/table'
    | '/integration/tanstack-query'
    | '/demo/chat'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/base/http/xhr'
    | '/integration/api/mcp-todos'
    | '/integration/better-auth/webauthn'
    | '/integration/form/address'
    | '/integration/form/simple'
    | '/integration/guitars/$guitarId'
    | '/integration/i18n/paraglide'
    | '/integration/orpc/todo'
    | '/integration/tanstack-db/chat'
    | '/integration/tanstack-db/chat-api'
    | '/integration/tanstack-db/error'
    | '/integration/zod/file'
    | '/ui/action/button'
    | '/base/s3/'
    | '/demo/chat/'
    | '/integration/better-auth/'
    | '/integration/guitars/'
    | '/base/http/api/err'
    | '/demo/chat/dm'
    | '/integration/api/ai/chat'
    | '/integration/api/ai/image'
    | '/integration/api/ai/structured'
    | '/integration/api/ai/transcription'
    | '/integration/api/ai/tts'
    | '/ui/display/md/tiptap'
    | '/ui/display/md/'
    | '/ui/display/md/prosemirror/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/mcp'
    | '/api/$'
    | '/api/friend_request'
    | '/api/message'
    | '/api/todo'
    | '/demo/todo'
    | '/integration/ai-chat'
    | '/integration/ai-image'
    | '/integration/ai-structured'
    | '/integration/drizzle'
    | '/integration/mcp-todos'
    | '/integration/store'
    | '/integration/table'
    | '/integration/tanstack-query'
    | '/demo/chat'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/base/http/xhr'
    | '/integration/api/mcp-todos'
    | '/integration/better-auth/webauthn'
    | '/integration/form/address'
    | '/integration/form/simple'
    | '/integration/guitars/$guitarId'
    | '/integration/i18n/paraglide'
    | '/integration/orpc/todo'
    | '/integration/tanstack-db/chat'
    | '/integration/tanstack-db/chat-api'
    | '/integration/tanstack-db/error'
    | '/integration/zod/file'
    | '/ui/action/button'
    | '/base/s3'
    | '/integration/better-auth'
    | '/integration/guitars'
    | '/base/http/api/err'
    | '/demo/chat/dm'
    | '/integration/api/ai/chat'
    | '/integration/api/ai/image'
    | '/integration/api/ai/structured'
    | '/integration/api/ai/transcription'
    | '/integration/api/ai/tts'
    | '/ui/display/md/tiptap'
    | '/ui/display/md'
    | '/ui/display/md/prosemirror'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/mcp'
    | '/api/$'
    | '/api/friend_request'
    | '/api/message'
    | '/api/todo'
    | '/demo/todo'
    | '/integration/ai-chat'
    | '/integration/ai-image'
    | '/integration/ai-structured'
    | '/integration/drizzle'
    | '/integration/mcp-todos'
    | '/integration/store'
    | '/integration/table'
    | '/integration/tanstack-query'
    | '/demo/chat/_dm'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/base/http/xhr'
    | '/integration/api/mcp-todos'
    | '/integration/better-auth/webauthn'
    | '/integration/form/address'
    | '/integration/form/simple'
    | '/integration/guitars/$guitarId'
    | '/integration/i18n/paraglide'
    | '/integration/orpc/todo'
    | '/integration/tanstack-db/chat'
    | '/integration/tanstack-db/chat-api'
    | '/integration/tanstack-db/error'
    | '/integration/zod/file'
    | '/ui/action/button'
    | '/base/s3/'
    | '/demo/chat/'
    | '/integration/better-auth/'
    | '/integration/guitars/'
    | '/base/http/api/err'
    | '/demo/chat/_dm/dm'
    | '/integration/api/ai/chat'
    | '/integration/api/ai/image'
    | '/integration/api/ai/structured'
    | '/integration/api/ai/transcription'
    | '/integration/api/ai/tts'
    | '/ui/display/md/tiptap'
    | '/ui/display/md/'
    | '/ui/display/md/prosemirror/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  McpRoute: typeof McpRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiFriend_requestRoute: typeof ApiFriend_requestRoute
  ApiMessageRoute: typeof ApiMessageRoute
  ApiTodoRoute: typeof ApiTodoRoute
  DemoTodoRoute: typeof DemoTodoRoute
  IntegrationAiChatRoute: typeof IntegrationAiChatRoute
  IntegrationAiImageRoute: typeof IntegrationAiImageRoute
  IntegrationAiStructuredRoute: typeof IntegrationAiStructuredRoute
  IntegrationDrizzleRoute: typeof IntegrationDrizzleRoute
  IntegrationMcpTodosRoute: typeof IntegrationMcpTodosRoute
  IntegrationStoreRoute: typeof IntegrationStoreRoute
  IntegrationTableRoute: typeof IntegrationTableRoute
  IntegrationTanstackQueryRoute: typeof IntegrationTanstackQueryRoute
  DemoChatDmRouteRoute: typeof DemoChatDmRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  BaseHttpXhrRoute: typeof BaseHttpXhrRoute
  IntegrationApiMcpTodosRoute: typeof IntegrationApiMcpTodosRoute
  IntegrationBetterAuthWebauthnRoute: typeof IntegrationBetterAuthWebauthnRoute
  IntegrationFormAddressRoute: typeof IntegrationFormAddressRoute
  IntegrationFormSimpleRoute: typeof IntegrationFormSimpleRoute
  IntegrationGuitarsGuitarIdRoute: typeof IntegrationGuitarsGuitarIdRoute
  IntegrationI18nParaglideRoute: typeof IntegrationI18nParaglideRoute
  IntegrationOrpcTodoRoute: typeof IntegrationOrpcTodoRoute
  IntegrationTanstackDbChatRoute: typeof IntegrationTanstackDbChatRoute
  IntegrationTanstackDbChatApiRoute: typeof IntegrationTanstackDbChatApiRoute
  IntegrationTanstackDbErrorRoute: typeof IntegrationTanstackDbErrorRoute
  IntegrationZodFileRoute: typeof IntegrationZodFileRoute
  UiActionButtonRoute: typeof UiActionButtonRoute
  BaseS3IndexRoute: typeof BaseS3IndexRoute
  DemoChatIndexRoute: typeof DemoChatIndexRoute
  IntegrationBetterAuthIndexRoute: typeof IntegrationBetterAuthIndexRoute
  IntegrationGuitarsIndexRoute: typeof IntegrationGuitarsIndexRoute
  BaseHttpApiErrRoute: typeof BaseHttpApiErrRoute
  IntegrationApiAiChatRoute: typeof IntegrationApiAiChatRoute
  IntegrationApiAiImageRoute: typeof IntegrationApiAiImageRoute
  IntegrationApiAiStructuredRoute: typeof IntegrationApiAiStructuredRoute
  IntegrationApiAiTranscriptionRoute: typeof IntegrationApiAiTranscriptionRoute
  IntegrationApiAiTtsRoute: typeof IntegrationApiAiTtsRoute
  UiDisplayMdTiptapRoute: typeof UiDisplayMdTiptapRoute
  UiDisplayMdIndexRoute: typeof UiDisplayMdIndexRoute
  UiDisplayMdProsemirrorIndexRoute: typeof UiDisplayMdProsemirrorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/tanstack-query': {
      id: '/integration/tanstack-query'
      path: '/integration/tanstack-query'
      fullPath: '/integration/tanstack-query'
      preLoaderRoute: typeof IntegrationTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/table': {
      id: '/integration/table'
      path: '/integration/table'
      fullPath: '/integration/table'
      preLoaderRoute: typeof IntegrationTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/store': {
      id: '/integration/store'
      path: '/integration/store'
      fullPath: '/integration/store'
      preLoaderRoute: typeof IntegrationStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/mcp-todos': {
      id: '/integration/mcp-todos'
      path: '/integration/mcp-todos'
      fullPath: '/integration/mcp-todos'
      preLoaderRoute: typeof IntegrationMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/drizzle': {
      id: '/integration/drizzle'
      path: '/integration/drizzle'
      fullPath: '/integration/drizzle'
      preLoaderRoute: typeof IntegrationDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/ai-structured': {
      id: '/integration/ai-structured'
      path: '/integration/ai-structured'
      fullPath: '/integration/ai-structured'
      preLoaderRoute: typeof IntegrationAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/ai-image': {
      id: '/integration/ai-image'
      path: '/integration/ai-image'
      fullPath: '/integration/ai-image'
      preLoaderRoute: typeof IntegrationAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/ai-chat': {
      id: '/integration/ai-chat'
      path: '/integration/ai-chat'
      fullPath: '/integration/ai-chat'
      preLoaderRoute: typeof IntegrationAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/todo': {
      id: '/demo/todo'
      path: '/demo/todo'
      fullPath: '/demo/todo'
      preLoaderRoute: typeof DemoTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todo': {
      id: '/api/todo'
      path: '/api/todo'
      fullPath: '/api/todo'
      preLoaderRoute: typeof ApiTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/message': {
      id: '/api/message'
      path: '/api/message'
      fullPath: '/api/message'
      preLoaderRoute: typeof ApiMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friend_request': {
      id: '/api/friend_request'
      path: '/api/friend_request'
      fullPath: '/api/friend_request'
      preLoaderRoute: typeof ApiFriend_requestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/guitars/': {
      id: '/integration/guitars/'
      path: '/integration/guitars'
      fullPath: '/integration/guitars/'
      preLoaderRoute: typeof IntegrationGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/better-auth/': {
      id: '/integration/better-auth/'
      path: '/integration/better-auth'
      fullPath: '/integration/better-auth/'
      preLoaderRoute: typeof IntegrationBetterAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/chat/': {
      id: '/demo/chat/'
      path: '/demo/chat'
      fullPath: '/demo/chat/'
      preLoaderRoute: typeof DemoChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/s3/': {
      id: '/base/s3/'
      path: '/base/s3'
      fullPath: '/base/s3/'
      preLoaderRoute: typeof BaseS3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/action/button': {
      id: '/ui/action/button'
      path: '/ui/action/button'
      fullPath: '/ui/action/button'
      preLoaderRoute: typeof UiActionButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/zod/file': {
      id: '/integration/zod/file'
      path: '/integration/zod/file'
      fullPath: '/integration/zod/file'
      preLoaderRoute: typeof IntegrationZodFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/tanstack-db/error': {
      id: '/integration/tanstack-db/error'
      path: '/integration/tanstack-db/error'
      fullPath: '/integration/tanstack-db/error'
      preLoaderRoute: typeof IntegrationTanstackDbErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/tanstack-db/chat-api': {
      id: '/integration/tanstack-db/chat-api'
      path: '/integration/tanstack-db/chat-api'
      fullPath: '/integration/tanstack-db/chat-api'
      preLoaderRoute: typeof IntegrationTanstackDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/tanstack-db/chat': {
      id: '/integration/tanstack-db/chat'
      path: '/integration/tanstack-db/chat'
      fullPath: '/integration/tanstack-db/chat'
      preLoaderRoute: typeof IntegrationTanstackDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/orpc/todo': {
      id: '/integration/orpc/todo'
      path: '/integration/orpc/todo'
      fullPath: '/integration/orpc/todo'
      preLoaderRoute: typeof IntegrationOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/i18n/paraglide': {
      id: '/integration/i18n/paraglide'
      path: '/integration/i18n/paraglide'
      fullPath: '/integration/i18n/paraglide'
      preLoaderRoute: typeof IntegrationI18nParaglideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/guitars/$guitarId': {
      id: '/integration/guitars/$guitarId'
      path: '/integration/guitars/$guitarId'
      fullPath: '/integration/guitars/$guitarId'
      preLoaderRoute: typeof IntegrationGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/form/simple': {
      id: '/integration/form/simple'
      path: '/integration/form/simple'
      fullPath: '/integration/form/simple'
      preLoaderRoute: typeof IntegrationFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/form/address': {
      id: '/integration/form/address'
      path: '/integration/form/address'
      fullPath: '/integration/form/address'
      preLoaderRoute: typeof IntegrationFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/better-auth/webauthn': {
      id: '/integration/better-auth/webauthn'
      path: '/integration/better-auth/webauthn'
      fullPath: '/integration/better-auth/webauthn'
      preLoaderRoute: typeof IntegrationBetterAuthWebauthnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/api/mcp-todos': {
      id: '/integration/api/mcp-todos'
      path: '/integration/api/mcp-todos'
      fullPath: '/integration/api/mcp-todos'
      preLoaderRoute: typeof IntegrationApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/http/xhr': {
      id: '/base/http/xhr'
      path: '/base/http/xhr'
      fullPath: '/base/http/xhr'
      preLoaderRoute: typeof BaseHttpXhrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/chat/_dm': {
      id: '/demo/chat/_dm'
      path: '/demo/chat'
      fullPath: '/demo/chat'
      preLoaderRoute: typeof DemoChatDmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/display/md/': {
      id: '/ui/display/md/'
      path: '/ui/display/md'
      fullPath: '/ui/display/md/'
      preLoaderRoute: typeof UiDisplayMdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/display/md/tiptap': {
      id: '/ui/display/md/tiptap'
      path: '/ui/display/md/tiptap'
      fullPath: '/ui/display/md/tiptap'
      preLoaderRoute: typeof UiDisplayMdTiptapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/api/ai/tts': {
      id: '/integration/api/ai/tts'
      path: '/integration/api/ai/tts'
      fullPath: '/integration/api/ai/tts'
      preLoaderRoute: typeof IntegrationApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/api/ai/transcription': {
      id: '/integration/api/ai/transcription'
      path: '/integration/api/ai/transcription'
      fullPath: '/integration/api/ai/transcription'
      preLoaderRoute: typeof IntegrationApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/api/ai/structured': {
      id: '/integration/api/ai/structured'
      path: '/integration/api/ai/structured'
      fullPath: '/integration/api/ai/structured'
      preLoaderRoute: typeof IntegrationApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/api/ai/image': {
      id: '/integration/api/ai/image'
      path: '/integration/api/ai/image'
      fullPath: '/integration/api/ai/image'
      preLoaderRoute: typeof IntegrationApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/api/ai/chat': {
      id: '/integration/api/ai/chat'
      path: '/integration/api/ai/chat'
      fullPath: '/integration/api/ai/chat'
      preLoaderRoute: typeof IntegrationApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/chat/_dm/dm': {
      id: '/demo/chat/_dm/dm'
      path: '/dm'
      fullPath: '/demo/chat/dm'
      preLoaderRoute: typeof DemoChatDmDmRouteImport
      parentRoute: typeof DemoChatDmRouteRoute
    }
    '/base/http/api/err': {
      id: '/base/http/api/err'
      path: '/base/http/api/err'
      fullPath: '/base/http/api/err'
      preLoaderRoute: typeof BaseHttpApiErrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/display/md/prosemirror/': {
      id: '/ui/display/md/prosemirror/'
      path: '/ui/display/md/prosemirror'
      fullPath: '/ui/display/md/prosemirror/'
      preLoaderRoute: typeof UiDisplayMdProsemirrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DemoChatDmRouteRouteChildren {
  DemoChatDmDmRoute: typeof DemoChatDmDmRoute
}

const DemoChatDmRouteRouteChildren: DemoChatDmRouteRouteChildren = {
  DemoChatDmDmRoute: DemoChatDmDmRoute,
}

const DemoChatDmRouteRouteWithChildren = DemoChatDmRouteRoute._addFileChildren(
  DemoChatDmRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  McpRoute: McpRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiFriend_requestRoute: ApiFriend_requestRoute,
  ApiMessageRoute: ApiMessageRoute,
  ApiTodoRoute: ApiTodoRoute,
  DemoTodoRoute: DemoTodoRoute,
  IntegrationAiChatRoute: IntegrationAiChatRoute,
  IntegrationAiImageRoute: IntegrationAiImageRoute,
  IntegrationAiStructuredRoute: IntegrationAiStructuredRoute,
  IntegrationDrizzleRoute: IntegrationDrizzleRoute,
  IntegrationMcpTodosRoute: IntegrationMcpTodosRoute,
  IntegrationStoreRoute: IntegrationStoreRoute,
  IntegrationTableRoute: IntegrationTableRoute,
  IntegrationTanstackQueryRoute: IntegrationTanstackQueryRoute,
  DemoChatDmRouteRoute: DemoChatDmRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  BaseHttpXhrRoute: BaseHttpXhrRoute,
  IntegrationApiMcpTodosRoute: IntegrationApiMcpTodosRoute,
  IntegrationBetterAuthWebauthnRoute: IntegrationBetterAuthWebauthnRoute,
  IntegrationFormAddressRoute: IntegrationFormAddressRoute,
  IntegrationFormSimpleRoute: IntegrationFormSimpleRoute,
  IntegrationGuitarsGuitarIdRoute: IntegrationGuitarsGuitarIdRoute,
  IntegrationI18nParaglideRoute: IntegrationI18nParaglideRoute,
  IntegrationOrpcTodoRoute: IntegrationOrpcTodoRoute,
  IntegrationTanstackDbChatRoute: IntegrationTanstackDbChatRoute,
  IntegrationTanstackDbChatApiRoute: IntegrationTanstackDbChatApiRoute,
  IntegrationTanstackDbErrorRoute: IntegrationTanstackDbErrorRoute,
  IntegrationZodFileRoute: IntegrationZodFileRoute,
  UiActionButtonRoute: UiActionButtonRoute,
  BaseS3IndexRoute: BaseS3IndexRoute,
  DemoChatIndexRoute: DemoChatIndexRoute,
  IntegrationBetterAuthIndexRoute: IntegrationBetterAuthIndexRoute,
  IntegrationGuitarsIndexRoute: IntegrationGuitarsIndexRoute,
  BaseHttpApiErrRoute: BaseHttpApiErrRoute,
  IntegrationApiAiChatRoute: IntegrationApiAiChatRoute,
  IntegrationApiAiImageRoute: IntegrationApiAiImageRoute,
  IntegrationApiAiStructuredRoute: IntegrationApiAiStructuredRoute,
  IntegrationApiAiTranscriptionRoute: IntegrationApiAiTranscriptionRoute,
  IntegrationApiAiTtsRoute: IntegrationApiAiTtsRoute,
  UiDisplayMdTiptapRoute: UiDisplayMdTiptapRoute,
  UiDisplayMdIndexRoute: UiDisplayMdIndexRoute,
  UiDisplayMdProsemirrorIndexRoute: UiDisplayMdProsemirrorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
