/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo.store'
import { Route as DemoSolidRouteImport } from './routes/demo/solid'
import { Route as DemoFormRouteImport } from './routes/demo/form'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as AdminV1IndexRouteImport } from './routes/admin/v1/index'
import { Route as AdminV0IndexRouteImport } from './routes/admin/v0/index'
import { Route as AdminSseIndexRouteImport } from './routes/admin/sse/index'
import { Route as AdminScreenShareIndexRouteImport } from './routes/admin/screen-share/index'
import { Route as AdminS1IndexRouteImport } from './routes/admin/s1/index'
import { Route as AdminPubsubIndexRouteImport } from './routes/admin/pubsub/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminV1SignalRouteImport } from './routes/admin/v1/signal'
import { Route as AdminV0SignalRouteImport } from './routes/admin/v0/signal'
import { Route as AdminSseChatApiRouteImport } from './routes/admin/sse/chat-api'
import { Route as AdminS1SignalRouteImport } from './routes/admin/s1/signal'
import { Route as AdminPubsubApiRouteImport } from './routes/admin/pubsub/api'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSolidRoute = DemoSolidRouteImport.update({
  id: '/demo/solid',
  path: '/demo/solid',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminV1IndexRoute = AdminV1IndexRouteImport.update({
  id: '/v1/',
  path: '/v1/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminV0IndexRoute = AdminV0IndexRouteImport.update({
  id: '/v0/',
  path: '/v0/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSseIndexRoute = AdminSseIndexRouteImport.update({
  id: '/sse/',
  path: '/sse/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScreenShareIndexRoute = AdminScreenShareIndexRouteImport.update({
  id: '/screen-share/',
  path: '/screen-share/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminS1IndexRoute = AdminS1IndexRouteImport.update({
  id: '/s1/',
  path: '/s1/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPubsubIndexRoute = AdminPubsubIndexRouteImport.update({
  id: '/pubsub/',
  path: '/pubsub/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminV1SignalRoute = AdminV1SignalRouteImport.update({
  id: '/v1/signal',
  path: '/v1/signal',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminV0SignalRoute = AdminV0SignalRouteImport.update({
  id: '/v0/signal',
  path: '/v0/signal',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSseChatApiRoute = AdminSseChatApiRouteImport.update({
  id: '/sse/chat-api',
  path: '/sse/chat-api',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminS1SignalRoute = AdminS1SignalRouteImport.update({
  id: '/s1/signal',
  path: '/s1/signal',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPubsubApiRoute = AdminPubsubApiRouteImport.update({
  id: '/pubsub/api',
  path: '/pubsub/api',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthAuthRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/solid': typeof DemoSolidRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pubsub/api': typeof AdminPubsubApiRoute
  '/admin/s1/signal': typeof AdminS1SignalRoute
  '/admin/sse/chat-api': typeof AdminSseChatApiRoute
  '/admin/v0/signal': typeof AdminV0SignalRoute
  '/admin/v1/signal': typeof AdminV1SignalRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/pubsub/': typeof AdminPubsubIndexRoute
  '/admin/s1/': typeof AdminS1IndexRoute
  '/admin/screen-share/': typeof AdminScreenShareIndexRoute
  '/admin/sse/': typeof AdminSseIndexRoute
  '/admin/v0/': typeof AdminV0IndexRoute
  '/admin/v1/': typeof AdminV1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/auth': typeof AuthAuthRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/solid': typeof DemoSolidRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pubsub/api': typeof AdminPubsubApiRoute
  '/admin/s1/signal': typeof AdminS1SignalRoute
  '/admin/sse/chat-api': typeof AdminSseChatApiRoute
  '/admin/v0/signal': typeof AdminV0SignalRoute
  '/admin/v1/signal': typeof AdminV1SignalRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/pubsub': typeof AdminPubsubIndexRoute
  '/admin/s1': typeof AdminS1IndexRoute
  '/admin/screen-share': typeof AdminScreenShareIndexRoute
  '/admin/sse': typeof AdminSseIndexRoute
  '/admin/v0': typeof AdminV0IndexRoute
  '/admin/v1': typeof AdminV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth/auth': typeof AuthAuthRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/solid': typeof DemoSolidRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pubsub/api': typeof AdminPubsubApiRoute
  '/admin/s1/signal': typeof AdminS1SignalRoute
  '/admin/sse/chat-api': typeof AdminSseChatApiRoute
  '/admin/v0/signal': typeof AdminV0SignalRoute
  '/admin/v1/signal': typeof AdminV1SignalRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/pubsub/': typeof AdminPubsubIndexRoute
  '/admin/s1/': typeof AdminS1IndexRoute
  '/admin/screen-share/': typeof AdminScreenShareIndexRoute
  '/admin/sse/': typeof AdminSseIndexRoute
  '/admin/v0/': typeof AdminV0IndexRoute
  '/admin/v1/': typeof AdminV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/demo/form'
    | '/demo/solid'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/admin/'
    | '/admin/pubsub/api'
    | '/admin/s1/signal'
    | '/admin/sse/chat-api'
    | '/admin/v0/signal'
    | '/admin/v1/signal'
    | '/api/auth/$'
    | '/admin/pubsub/'
    | '/admin/s1/'
    | '/admin/screen-share/'
    | '/admin/sse/'
    | '/admin/v0/'
    | '/admin/v1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo/form'
    | '/demo/solid'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/admin'
    | '/admin/pubsub/api'
    | '/admin/s1/signal'
    | '/admin/sse/chat-api'
    | '/admin/v0/signal'
    | '/admin/v1/signal'
    | '/api/auth/$'
    | '/admin/pubsub'
    | '/admin/s1'
    | '/admin/screen-share'
    | '/admin/sse'
    | '/admin/v0'
    | '/admin/v1'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/admin'
    | '/_auth/auth'
    | '/demo/form'
    | '/demo/solid'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/_main/'
    | '/admin/'
    | '/admin/pubsub/api'
    | '/admin/s1/signal'
    | '/admin/sse/chat-api'
    | '/admin/v0/signal'
    | '/admin/v1/signal'
    | '/api/auth/$'
    | '/admin/pubsub/'
    | '/admin/s1/'
    | '/admin/screen-share/'
    | '/admin/sse/'
    | '/admin/v0/'
    | '/admin/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DemoFormRoute: typeof DemoFormRoute
  DemoSolidRoute: typeof DemoSolidRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/solid': {
      id: '/demo/solid'
      path: '/demo/solid'
      fullPath: '/demo/solid'
      preLoaderRoute: typeof DemoSolidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/v1/': {
      id: '/admin/v1/'
      path: '/v1'
      fullPath: '/admin/v1/'
      preLoaderRoute: typeof AdminV1IndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/v0/': {
      id: '/admin/v0/'
      path: '/v0'
      fullPath: '/admin/v0/'
      preLoaderRoute: typeof AdminV0IndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sse/': {
      id: '/admin/sse/'
      path: '/sse'
      fullPath: '/admin/sse/'
      preLoaderRoute: typeof AdminSseIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/screen-share/': {
      id: '/admin/screen-share/'
      path: '/screen-share'
      fullPath: '/admin/screen-share/'
      preLoaderRoute: typeof AdminScreenShareIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/s1/': {
      id: '/admin/s1/'
      path: '/s1'
      fullPath: '/admin/s1/'
      preLoaderRoute: typeof AdminS1IndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pubsub/': {
      id: '/admin/pubsub/'
      path: '/pubsub'
      fullPath: '/admin/pubsub/'
      preLoaderRoute: typeof AdminPubsubIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/v1/signal': {
      id: '/admin/v1/signal'
      path: '/v1/signal'
      fullPath: '/admin/v1/signal'
      preLoaderRoute: typeof AdminV1SignalRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/v0/signal': {
      id: '/admin/v0/signal'
      path: '/v0/signal'
      fullPath: '/admin/v0/signal'
      preLoaderRoute: typeof AdminV0SignalRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sse/chat-api': {
      id: '/admin/sse/chat-api'
      path: '/sse/chat-api'
      fullPath: '/admin/sse/chat-api'
      preLoaderRoute: typeof AdminSseChatApiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/s1/signal': {
      id: '/admin/s1/signal'
      path: '/s1/signal'
      fullPath: '/admin/s1/signal'
      preLoaderRoute: typeof AdminS1SignalRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pubsub/api': {
      id: '/admin/pubsub/api'
      path: '/pubsub/api'
      fullPath: '/admin/pubsub/api'
      preLoaderRoute: typeof AdminPubsubApiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPubsubApiRoute: typeof AdminPubsubApiRoute
  AdminS1SignalRoute: typeof AdminS1SignalRoute
  AdminSseChatApiRoute: typeof AdminSseChatApiRoute
  AdminV0SignalRoute: typeof AdminV0SignalRoute
  AdminV1SignalRoute: typeof AdminV1SignalRoute
  AdminPubsubIndexRoute: typeof AdminPubsubIndexRoute
  AdminS1IndexRoute: typeof AdminS1IndexRoute
  AdminScreenShareIndexRoute: typeof AdminScreenShareIndexRoute
  AdminSseIndexRoute: typeof AdminSseIndexRoute
  AdminV0IndexRoute: typeof AdminV0IndexRoute
  AdminV1IndexRoute: typeof AdminV1IndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPubsubApiRoute: AdminPubsubApiRoute,
  AdminS1SignalRoute: AdminS1SignalRoute,
  AdminSseChatApiRoute: AdminSseChatApiRoute,
  AdminV0SignalRoute: AdminV0SignalRoute,
  AdminV1SignalRoute: AdminV1SignalRoute,
  AdminPubsubIndexRoute: AdminPubsubIndexRoute,
  AdminS1IndexRoute: AdminS1IndexRoute,
  AdminScreenShareIndexRoute: AdminScreenShareIndexRoute,
  AdminSseIndexRoute: AdminSseIndexRoute,
  AdminV0IndexRoute: AdminV0IndexRoute,
  AdminV1IndexRoute: AdminV1IndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DemoFormRoute: DemoFormRoute,
  DemoSolidRoute: DemoSolidRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
