/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo.store'
import { Route as DemoSolidRouteImport } from './routes/demo/solid'
import { Route as DemoFormRouteImport } from './routes/demo.form'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as AdminSseIndexRouteImport } from './routes/admin/sse/index'
import { Route as AdminScreenShareIndexRouteImport } from './routes/admin/screen-share/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminSseChatApiRouteImport } from './routes/admin/sse/chat-api'
import { Route as AdminScreenShareSignalRouteImport } from './routes/admin/screen-share/signal'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSolidRoute = DemoSolidRouteImport.update({
  id: '/demo/solid',
  path: '/demo/solid',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminSseIndexRoute = AdminSseIndexRouteImport.update({
  id: '/sse/',
  path: '/sse/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScreenShareIndexRoute = AdminScreenShareIndexRouteImport.update({
  id: '/screen-share/',
  path: '/screen-share/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSseChatApiRoute = AdminSseChatApiRouteImport.update({
  id: '/sse/chat-api',
  path: '/sse/chat-api',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScreenShareSignalRoute = AdminScreenShareSignalRouteImport.update({
  id: '/screen-share/signal',
  path: '/screen-share/signal',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthAuthRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/solid': typeof DemoSolidRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/screen-share/signal': typeof AdminScreenShareSignalRoute
  '/admin/sse/chat-api': typeof AdminSseChatApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/screen-share/': typeof AdminScreenShareIndexRoute
  '/admin/sse/': typeof AdminSseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/auth': typeof AuthAuthRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/solid': typeof DemoSolidRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin': typeof AdminIndexRoute
  '/admin/screen-share/signal': typeof AdminScreenShareSignalRoute
  '/admin/sse/chat-api': typeof AdminSseChatApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/screen-share': typeof AdminScreenShareIndexRoute
  '/admin/sse': typeof AdminSseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth/auth': typeof AuthAuthRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/solid': typeof DemoSolidRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/screen-share/signal': typeof AdminScreenShareSignalRoute
  '/admin/sse/chat-api': typeof AdminSseChatApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/screen-share/': typeof AdminScreenShareIndexRoute
  '/admin/sse/': typeof AdminSseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/demo/form'
    | '/demo/solid'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/admin/'
    | '/admin/screen-share/signal'
    | '/admin/sse/chat-api'
    | '/api/auth/$'
    | '/admin/screen-share/'
    | '/admin/sse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo/form'
    | '/demo/solid'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/admin'
    | '/admin/screen-share/signal'
    | '/admin/sse/chat-api'
    | '/api/auth/$'
    | '/admin/screen-share'
    | '/admin/sse'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/admin'
    | '/_auth/auth'
    | '/demo/form'
    | '/demo/solid'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/_main/'
    | '/admin/'
    | '/admin/screen-share/signal'
    | '/admin/sse/chat-api'
    | '/api/auth/$'
    | '/admin/screen-share/'
    | '/admin/sse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DemoFormRoute: typeof DemoFormRoute
  DemoSolidRoute: typeof DemoSolidRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/solid': {
      id: '/demo/solid'
      path: '/demo/solid'
      fullPath: '/demo/solid'
      preLoaderRoute: typeof DemoSolidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/sse/': {
      id: '/admin/sse/'
      path: '/sse'
      fullPath: '/admin/sse/'
      preLoaderRoute: typeof AdminSseIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/screen-share/': {
      id: '/admin/screen-share/'
      path: '/screen-share'
      fullPath: '/admin/screen-share/'
      preLoaderRoute: typeof AdminScreenShareIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sse/chat-api': {
      id: '/admin/sse/chat-api'
      path: '/sse/chat-api'
      fullPath: '/admin/sse/chat-api'
      preLoaderRoute: typeof AdminSseChatApiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/screen-share/signal': {
      id: '/admin/screen-share/signal'
      path: '/screen-share/signal'
      fullPath: '/admin/screen-share/signal'
      preLoaderRoute: typeof AdminScreenShareSignalRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminScreenShareSignalRoute: typeof AdminScreenShareSignalRoute
  AdminSseChatApiRoute: typeof AdminSseChatApiRoute
  AdminScreenShareIndexRoute: typeof AdminScreenShareIndexRoute
  AdminSseIndexRoute: typeof AdminSseIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminScreenShareSignalRoute: AdminScreenShareSignalRoute,
  AdminSseChatApiRoute: AdminSseChatApiRoute,
  AdminScreenShareIndexRoute: AdminScreenShareIndexRoute,
  AdminSseIndexRoute: AdminSseIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DemoFormRoute: DemoFormRoute,
  DemoSolidRoute: DemoSolidRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
