export const serverEnv = {
	DATABASE_URL: process.env.DATABASE_URL!,
	BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET!,
	ELECTRIC_SOURCE_ID: process.env.ELECTRIC_SOURCE_ID!,
	ELECTRIC_SECRET: process.env.ELECTRIC_SECRET!,
	// R2_S3_ENDPOINT: process.env.R2_S3_ENDPOINT,
	// R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID,
	// R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
	// R2_BUCKET_NAME: process.env.R2_BUCKET_NAME,
	// R2_SESSION_TOKEN: process.env.R2_SESSION_TOKEN,
};
